import type {
  Account,
  DailySnapshot,
  Profile,
  Strategy,
  Trade,
  TradeExecution,
  TradeNote,
  TradeTag,
} from "@/lib/types";

export const profile: Profile = {
  id: "user-1",
  fullName: "Alex Rivera",
  email: "alex@chartlore.app",
  tier: "elite",
  initials: "AR",
  focus: "Index futures, equity momentum, and intraday mean reversion.",
  country: "United States",
  phone: "+1 (415) 555-0124",
  city: "New York",
  timezone: "America/New_York",
};

export const accounts: Account[] = [
  {
    id: "acct-futures",
    userId: profile.id,
    name: "Prime Futures",
    broker: "Interactive Brokers",
    balance: 142508.42,
    currency: "USD",
    type: "futures",
  },
  {
    id: "acct-equities",
    userId: profile.id,
    name: "Momentum Equity",
    broker: "Alpaca",
    balance: 84210.1,
    currency: "USD",
    type: "equities",
  },
];

export const strategies: Strategy[] = [
  {
    id: "strategy-breakout",
    userId: profile.id,
    name: "Volatility Breakout",
    slug: "volatility-breakout",
    status: "active",
    playbook: "2m Opening Range",
    thesis: "Capture expansion after compression with opening drive confirmation.",
    timeframes: ["2m", "5m", "15m"],
    tags: ["opening drive", "futures"],
  },
  {
    id: "strategy-mean-reversion",
    userId: profile.id,
    name: "Mean Reversion",
    slug: "mean-reversion",
    status: "active",
    playbook: "VWAP Bounce",
    thesis: "Fade extension into VWAP when liquidity and structure align.",
    timeframes: ["1m", "5m"],
    tags: ["vwap", "fade"],
  },
  {
    id: "strategy-trend",
    userId: profile.id,
    name: "Trend Continuation",
    slug: "trend-continuation",
    status: "active",
    playbook: "EMA Ladder",
    thesis: "Scale into continuation after higher low or lower high confirmation.",
    timeframes: ["5m", "15m", "1h"],
    tags: ["trend", "equities"],
  },
  {
    id: "strategy-news",
    userId: profile.id,
    name: "Catalyst Compression",
    slug: "catalyst-compression",
    status: "revising",
    playbook: "Headline Fade",
    thesis: "Trade post-news compression only when volatility resets and liquidity holds.",
    timeframes: ["1m", "5m"],
    tags: ["news", "beta"],
  },
];

export const tags: TradeTag[] = [
  { id: "tag-a-plus", label: "A+ Setup", tone: "success" },
  { id: "tag-open", label: "NY Open", tone: "accent" },
  { id: "tag-afternoon", label: "Afternoon", tone: "warning" },
  { id: "tag-fomo", label: "FOMO", tone: "danger" },
  { id: "tag-clean", label: "Clean Execution", tone: "neutral" },
];

export const tradeNotes: TradeNote[] = [
  {
    id: "note-1",
    tradeId: "trade-1",
    content:
      "Executed on first retest after opening drive. Limit order helped avoid 2.5 ticks of slippage.",
    createdAt: "2026-04-23T14:05:00.000Z",
  },
  {
    id: "note-2",
    tradeId: "trade-6",
    content:
      "Afternoon mean reversion failed once volume dried up. Reduce size or avoid post-lunch fades.",
    createdAt: "2026-04-18T17:15:00.000Z",
  },
  {
    id: "note-3",
    tradeId: "trade-10",
    content:
      "Strong trend continuation after semiconductor earnings. Need this tagged as sector momentum.",
    createdAt: "2026-04-26T18:31:00.000Z",
  },
];

export const tradeExecutions: TradeExecution[] = [
  {
    id: "exec-1",
    tradeId: "trade-1",
    quantity: 4,
    price: 15420.25,
    executedAt: "2026-04-23T13:34:00.000Z",
    kind: "entry",
  },
  {
    id: "exec-2",
    tradeId: "trade-1",
    quantity: 2,
    price: 15458.5,
    executedAt: "2026-04-23T13:46:00.000Z",
    kind: "partial_exit",
  },
  {
    id: "exec-3",
    tradeId: "trade-1",
    quantity: 2,
    price: 15482.75,
    executedAt: "2026-04-23T13:57:00.000Z",
    kind: "exit",
  },
  {
    id: "exec-4",
    tradeId: "trade-10",
    quantity: 150,
    price: 901.2,
    executedAt: "2026-04-26T16:05:00.000Z",
    kind: "entry",
  },
];

export const trades: Trade[] = [
  {
    id: "trade-1",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-breakout",
    symbol: "NQ1!",
    market: "Nasdaq 100 Futures",
    side: "long",
    quantity: 4,
    entryPrice: 15420.25,
    exitPrice: 15482.75,
    stopPrice: 15394.25,
    fees: 24,
    setup: "Opening Drive Breakout",
    thesis: "Compression resolved upward after opening range acceptance.",
    openedAt: "2026-04-23T13:34:00.000Z",
    closedAt: "2026-04-23T13:57:00.000Z",
    conviction: 5,
    tags: ["tag-a-plus", "tag-open", "tag-clean"],
    noteIds: ["note-1"],
    executionIds: ["exec-1", "exec-2", "exec-3"],
  },
  {
    id: "trade-2",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-mean-reversion",
    symbol: "ES1!",
    market: "S&P 500 Futures",
    side: "short",
    quantity: 3,
    entryPrice: 4412.5,
    exitPrice: 4408.25,
    stopPrice: 4416.75,
    fees: 18,
    setup: "VWAP Bounce Fade",
    thesis: "Failed reclaim into VWAP with weak delta.",
    openedAt: "2026-04-22T14:13:00.000Z",
    closedAt: "2026-04-22T14:31:00.000Z",
    conviction: 3,
    tags: ["tag-open"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-3",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-trend",
    symbol: "GC1!",
    market: "Gold Futures",
    side: "long",
    quantity: 2,
    entryPrice: 1942.1,
    exitPrice: 1958.4,
    stopPrice: 1937.0,
    fees: 12,
    setup: "EMA Continuation",
    thesis: "Daily trend aligned with intraday pullback into 20 EMA.",
    openedAt: "2026-04-20T15:12:00.000Z",
    closedAt: "2026-04-20T18:44:00.000Z",
    conviction: 4,
    tags: ["tag-clean"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-4",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-breakout",
    symbol: "CL1!",
    market: "Crude Oil Futures",
    side: "short",
    quantity: 2,
    entryPrice: 78.22,
    exitPrice: 78.22,
    stopPrice: 78.64,
    fees: 10,
    setup: "Range Break Failure",
    thesis: "Failed break at overnight high. Flattened at breakeven when tape stalled.",
    openedAt: "2026-04-19T14:05:00.000Z",
    closedAt: "2026-04-19T14:26:00.000Z",
    conviction: 2,
    tags: ["tag-afternoon"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-5",
    userId: profile.id,
    accountId: "acct-equities",
    strategyId: "strategy-trend",
    symbol: "NVDA",
    market: "NVIDIA",
    side: "long",
    quantity: 140,
    entryPrice: 124.5,
    exitPrice: 131.2,
    stopPrice: 121.8,
    fees: 14,
    setup: "High Tight Flag",
    thesis: "Flag continuation after earnings strength.",
    openedAt: "2026-04-24T14:41:00.000Z",
    closedAt: "2026-04-24T18:14:00.000Z",
    conviction: 5,
    tags: ["tag-a-plus", "tag-clean"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-6",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-mean-reversion",
    symbol: "RTY1!",
    market: "Russell 2000 Futures",
    side: "long",
    quantity: 2,
    entryPrice: 2241.7,
    exitPrice: 2237.3,
    stopPrice: 2237.2,
    fees: 12,
    setup: "Value Reclaim",
    thesis: "Tried to catch value area reclaim but breadth never confirmed.",
    openedAt: "2026-04-18T17:02:00.000Z",
    closedAt: "2026-04-18T17:19:00.000Z",
    conviction: 2,
    tags: ["tag-afternoon", "tag-fomo"],
    noteIds: ["note-2"],
    executionIds: [],
  },
  {
    id: "trade-7",
    userId: profile.id,
    accountId: "acct-equities",
    strategyId: "strategy-trend",
    symbol: "TSLA",
    market: "Tesla",
    side: "long",
    quantity: 200,
    entryPrice: 210.15,
    exitPrice: 225.4,
    stopPrice: 204.5,
    fees: 18,
    setup: "Trend Continuation",
    thesis: "Momentum follow-through after reclaiming daily VWAP.",
    openedAt: "2026-04-17T15:08:00.000Z",
    closedAt: "2026-04-17T19:46:00.000Z",
    conviction: 4,
    tags: ["tag-clean"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-8",
    userId: profile.id,
    accountId: "acct-equities",
    strategyId: "strategy-news",
    symbol: "AMD",
    market: "AMD",
    side: "short",
    quantity: 100,
    entryPrice: 181.4,
    exitPrice: 184.6,
    stopPrice: 184.2,
    fees: 12,
    setup: "Headline Fade",
    thesis: "Catalyst fade but no expansion follow-through.",
    openedAt: "2026-04-15T14:26:00.000Z",
    closedAt: "2026-04-15T15:11:00.000Z",
    conviction: 1,
    tags: ["tag-fomo"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-9",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-breakout",
    symbol: "BTCUSD",
    market: "Bitcoin Spot",
    side: "long",
    quantity: 0.8,
    entryPrice: 68240,
    exitPrice: 69910,
    stopPrice: 67380,
    fees: 26,
    setup: "Liquidity Sweep Breakout",
    thesis: "Asia high sweep followed by reclaim and volume expansion.",
    openedAt: "2026-04-14T08:04:00.000Z",
    closedAt: "2026-04-14T11:52:00.000Z",
    conviction: 4,
    tags: ["tag-a-plus"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-10",
    userId: profile.id,
    accountId: "acct-equities",
    strategyId: "strategy-trend",
    symbol: "AVGO",
    market: "Broadcom",
    side: "long",
    quantity: 150,
    entryPrice: 901.2,
    exitPrice: 923.8,
    stopPrice: 891.4,
    fees: 16,
    setup: "Post-Earnings Trend",
    thesis: "Semiconductor leadership remained intact after opening pullback.",
    openedAt: "2026-04-26T16:05:00.000Z",
    closedAt: "2026-04-26T18:28:00.000Z",
    conviction: 5,
    tags: ["tag-open", "tag-clean"],
    noteIds: ["note-3"],
    executionIds: ["exec-4"],
  },
  {
    id: "trade-11",
    userId: profile.id,
    accountId: "acct-futures",
    strategyId: "strategy-mean-reversion",
    symbol: "YM1!",
    market: "Dow Futures",
    side: "short",
    quantity: 3,
    entryPrice: 39822,
    exitPrice: 39671,
    stopPrice: 39910,
    fees: 18,
    setup: "Liquidity Fade",
    thesis: "Auction into prior day high failed once breadth turned negative.",
    openedAt: "2026-04-27T14:02:00.000Z",
    closedAt: "2026-04-27T15:04:00.000Z",
    conviction: 4,
    tags: ["tag-open", "tag-clean"],
    noteIds: [],
    executionIds: [],
  },
  {
    id: "trade-12",
    userId: profile.id,
    accountId: "acct-equities",
    strategyId: "strategy-news",
    symbol: "META",
    market: "Meta Platforms",
    side: "long",
    quantity: 80,
    entryPrice: 502.2,
    exitPrice: 496.4,
    stopPrice: 497.1,
    fees: 10,
    setup: "News Compression Break",
    thesis: "Tried to hold late-day news continuation but breadth collapsed.",
    openedAt: "2026-04-11T18:04:00.000Z",
    closedAt: "2026-04-11T19:03:00.000Z",
    conviction: 2,
    tags: ["tag-afternoon"],
    noteIds: [],
    executionIds: [],
  },
];

export const dailySnapshots: DailySnapshot[] = [
  { id: "snap-1", date: "2026-04-21", netPnl: 1840, accountBalance: 139902, drawdown: -1.8 },
  { id: "snap-2", date: "2026-04-22", netPnl: -420, accountBalance: 139482, drawdown: -2.2 },
  { id: "snap-3", date: "2026-04-23", netPnl: 2120, accountBalance: 141602, drawdown: -1.4 },
  { id: "snap-4", date: "2026-04-24", netPnl: 980, accountBalance: 142582, drawdown: -1.1 },
  { id: "snap-5", date: "2026-04-25", netPnl: 0, accountBalance: 142582, drawdown: -1.1 },
  { id: "snap-6", date: "2026-04-26", netPnl: 2410, accountBalance: 144992, drawdown: -0.4 },
  { id: "snap-7", date: "2026-04-27", netPnl: 1516, accountBalance: 146508, drawdown: 0 },
];
